jQuery(function($){
    $(document).ready(function(){
        $('#owlContent').owlCarousel({
            loop:true,
            margin:10,
            nav:false,
            responsive:{
                0:{
                    items:4
                },
                600:{
                    items:4
                },
                1000:{
                    items:4
                }
            }
        });
    });
});